"""empty message

Revision ID: b61c789e8a0c
Revises: b79ea191d69b
Create Date: 2025-02-07 14:59:20.038907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61c789e8a0c'
down_revision = 'b79ea191d69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###
